// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AdminConfigSessioncookie - Session cookie configuration details.
type AdminConfigSessioncookie struct {
	// SameSite attribute accepts three values:
	// * `Strict` - cookies will only be sent in a first-party context, not be sent along with requests initiated by third party websites.
	// * `Lax` - cookies are not sent on normal cross-site subrequests, but are sent when a user is navigating to the origin site.
	// * `None` - cookies will be sent in all contexts.
	//
	// Default value: `Lax`
	//
	Samesite *float64 `json:"samesite,omitempty"`
}
