// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BodyAndDownloadLinkGiven struct {
	// Both body data and download link were given.
	Err *string `json:"err,omitempty"`
}
