// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DownloadInfo - The downloading status.
type DownloadInfo struct {
	// Revealed detailed reason why the download failed.
	//
	ErrorDetail *string `json:"error_detail,omitempty"`
	// Only applicable when "status" is `Downloading`, indicates download finished percentage, in a range of [1, 99].
	//   * Once hitting 100, the status will be changed to `Download Success`.
	//   * or other problematic status (`Download Cancelled`, `Download Failed`) if the download stopped unexpectedly.
	//
	Progress *float64 `json:"progress,omitempty"`
	// Indicates download status, which could be either
	//   - `Downloading`
	//     - Check `progress` key value for actual download percentage
	//       ```json
	//       "download_info": {
	//           "progress": 7,
	//           "status": "Downloading",
	//           "url": "http://192.168.200.97:8080/5gb.zip"
	//       }
	//       ```
	//   - `Download Success`
	//       ```json
	//       "download_info": {
	//           "status": "Download Success",
	//           "url": "https://secure.eicar.org/eicar.com"
	//       }
	//       ```
	//   - `Download Failed`
	//     - Check `error_detail` key value for an error explanation
	//       ```json
	//       "download_info": {
	//           "error_detail": "Connection error",
	//           "status": "Download Failed",
	//           "url": "http://192.168.200.97:8080/2gb.zip"
	//       }
	//       ```
	//   - `Download Timeout`
	//     - Expecting to occur when the download progress takes longer than what time window allowed in MetaDefender Core's pre-configured setting under workflow rule (under "SCAN" tab)
	//       ```json
	//       "download_info": {
	//           "status": "Download Timeout",
	//           "url": "http://192.168.200.97:8080/2gb.zip"
	//       }
	//       ```
	//   - `Download Cancelled`
	//     - Expecting to occur when user explicitly cancelled that file scan request, or batch request that the scan belongs to
	//       ```json
	//       "download_info": {
	//           "status": "Download Cancelled",
	//           "url": "http://192.168.200.97:8080/5gb.zip"
	//       }
	//       ```
	//
	Status *string `json:"status,omitempty"`
	// Original download link which was specified in HTTP(S) request's `downloadfrom` header
	//
	URL *string `json:"url,omitempty"`
}
