// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ErrorWhileRequestingConfig struct {
	// Error while requesting configuration
	Err *string `json:"err,omitempty"`
}

func (o *ErrorWhileRequestingConfig) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}
