// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ExtractionInfoDecryptedStatus - Indicate that decryption phase is successful or not.
type ExtractionInfoDecryptedStatus string

const (
	ExtractionInfoDecryptedStatusSuccess ExtractionInfoDecryptedStatus = "Success"
	ExtractionInfoDecryptedStatusFailed  ExtractionInfoDecryptedStatus = "Failed"
)

func (e ExtractionInfoDecryptedStatus) ToPointer() *ExtractionInfoDecryptedStatus {
	return &e
}

func (e *ExtractionInfoDecryptedStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Success":
		fallthrough
	case "Failed":
		*e = ExtractionInfoDecryptedStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ExtractionInfoDecryptedStatus: %v", v)
	}
}

// ExtractionInfo - Details for archive extraction.
type ExtractionInfo struct {
	// Indicate that decryption phase is successful or not.
	DecryptedStatus *ExtractionInfoDecryptedStatus `json:"decrypted_status,omitempty"`
	// Error category
	ErrCategory *string `json:"err_category,omitempty"`
	// Error code
	ErrCode *int64 `json:"err_code,omitempty"`
	// Error message
	ErrDetails *string `json:"err_details,omitempty"`
	// Indicate if file is password-protected or not.
	IsEncryptedFile *bool `json:"is_encrypted_file,omitempty"`
}
