// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MissingEnabledField struct {
	// Missing enabled field
	Err *string `json:"err,omitempty"`
}

func (o *MissingEnabledField) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}
