// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MissingPort struct {
	// Missing port
	Err *string `json:"err,omitempty"`
}

func (o *MissingPort) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}
