// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PostlicenseKeyRequest - basic information
type PostlicenseKeyRequest struct {
	// The license key provided by OPSWAT (either eval or production license).
	ActivationKey *string `json:"activationKey,omitempty"`
	// Metadata field allowing you to provide relevant identification information for this instance.
	Comment *string `json:"comment,omitempty"`
	// The number of MetaDefender nodes attached to this instance.
	Quantity *int64 `json:"quantity,omitempty"`
}
