// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PostProxyRequest - basic information
type PostProxyRequest struct {
	// This redundant attribute will be removed soon.
	Enabled bool `json:"enabled"`
	// Not use the proxy server for the addresses starting with the following entries
	Exclusion *string `json:"exclusion,omitempty"`
	// Password for proxy authentication
	Password *string `json:"password,omitempty"`
	// Proxy server port
	Port string `json:"port"`
	// Proxy server host address
	Server string `json:"server"`
	// Username for proxy authentication
	Username *string `json:"username,omitempty"`
}

func (o *PostProxyRequest) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *PostProxyRequest) GetExclusion() *string {
	if o == nil {
		return nil
	}
	return o.Exclusion
}

func (o *PostProxyRequest) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *PostProxyRequest) GetPort() string {
	if o == nil {
		return ""
	}
	return o.Port
}

func (o *PostProxyRequest) GetServer() string {
	if o == nil {
		return ""
	}
	return o.Server
}

func (o *PostProxyRequest) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}
