// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PostRequestBody - Health check criterias.
type PostRequestBody struct {
	EnableFeature         *bool    `json:"enable_feature,omitempty"`
	NumberActiveAvEngines *int64   `json:"number_active_av_engines,omitempty"`
	RequiredEngines       []string `json:"required_engines,omitempty"`
	ScanQueue             *int64   `json:"scan_queue,omitempty"`
}

func (o *PostRequestBody) GetEnableFeature() *bool {
	if o == nil {
		return nil
	}
	return o.EnableFeature
}

func (o *PostRequestBody) GetNumberActiveAvEngines() *int64 {
	if o == nil {
		return nil
	}
	return o.NumberActiveAvEngines
}

func (o *PostRequestBody) GetRequiredEngines() []string {
	if o == nil {
		return nil
	}
	return o.RequiredEngines
}

func (o *PostRequestBody) GetScanQueue() *int64 {
	if o == nil {
		return nil
	}
	return o.ScanQueue
}
