// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ReadyzDatabase - Database connection
type ReadyzDatabase struct {
	// Connection status
	Status *bool `json:"status,omitempty"`
}

func (o *ReadyzDatabase) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

type ReadyzEngines struct {
	// Engine ID
	EngineID *string `json:"engine_id,omitempty"`
	// This engine is mandatorily active
	Required *bool `json:"required,omitempty"`
	// Status
	Status *bool `json:"status,omitempty"`
}

func (o *ReadyzEngines) GetEngineID() *string {
	if o == nil {
		return nil
	}
	return o.EngineID
}

func (o *ReadyzEngines) GetRequired() *bool {
	if o == nil {
		return nil
	}
	return o.Required
}

func (o *ReadyzEngines) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

// ReadyzLicenseStatus - License status
type ReadyzLicenseStatus string

const (
	ReadyzLicenseStatusExpired ReadyzLicenseStatus = "expired"
	ReadyzLicenseStatusInvalid ReadyzLicenseStatus = "invalid"
	ReadyzLicenseStatusOk      ReadyzLicenseStatus = "ok"
)

func (e ReadyzLicenseStatus) ToPointer() *ReadyzLicenseStatus {
	return &e
}

func (e *ReadyzLicenseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "expired":
		fallthrough
	case "invalid":
		fallthrough
	case "ok":
		*e = ReadyzLicenseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReadyzLicenseStatus: %v", v)
	}
}

// ReadyzLicense - License status
type ReadyzLicense struct {
	// License status
	Status *ReadyzLicenseStatus `json:"status,omitempty"`
}

func (o *ReadyzLicense) GetStatus() *ReadyzLicenseStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

// ReadyzNumberActiveAvEngines - Number of active AV engines
type ReadyzNumberActiveAvEngines struct {
	// Status
	Status *bool `json:"status,omitempty"`
	// User-defined threshold
	Threshold *int64 `json:"threshold,omitempty"`
}

func (o *ReadyzNumberActiveAvEngines) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ReadyzNumberActiveAvEngines) GetThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.Threshold
}

// ReadyzScanQueue - Scan queue status
type ReadyzScanQueue struct {
	// Maximum slots in scan queue
	MaxNumberInQueue *int64 `json:"max_number_in_queue,omitempty"`
	// Current queue status
	NumberInQueue *int64 `json:"number_in_queue,omitempty"`
	// status
	Status *bool `json:"status,omitempty"`
	// User-defined threshold
	Threshold *int64 `json:"threshold,omitempty"`
}

func (o *ReadyzScanQueue) GetMaxNumberInQueue() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxNumberInQueue
}

func (o *ReadyzScanQueue) GetNumberInQueue() *int64 {
	if o == nil {
		return nil
	}
	return o.NumberInQueue
}

func (o *ReadyzScanQueue) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ReadyzScanQueue) GetThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.Threshold
}

type Readyz struct {
	// Database connection
	Database *ReadyzDatabase `json:"database,omitempty"`
	// All available engines according to the activated license
	Engines []ReadyzEngines `json:"engines,omitempty"`
	// License status
	License *ReadyzLicense `json:"license,omitempty"`
	// Number of active AV engines
	NumberActiveAvEngines *ReadyzNumberActiveAvEngines `json:"number_active_av_engines,omitempty"`
	// Scan queue status
	ScanQueue *ReadyzScanQueue `json:"scan_queue,omitempty"`
}

func (o *Readyz) GetDatabase() *ReadyzDatabase {
	if o == nil {
		return nil
	}
	return o.Database
}

func (o *Readyz) GetEngines() []ReadyzEngines {
	if o == nil {
		return nil
	}
	return o.Engines
}

func (o *Readyz) GetLicense() *ReadyzLicense {
	if o == nil {
		return nil
	}
	return o.License
}

func (o *Readyz) GetNumberActiveAvEngines() *ReadyzNumberActiveAvEngines {
	if o == nil {
		return nil
	}
	return o.NumberActiveAvEngines
}

func (o *Readyz) GetScanQueue() *ReadyzScanQueue {
	if o == nil {
		return nil
	}
	return o.ScanQueue
}
