// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type RolePermissionObject string

const (
	RolePermissionObjectRead  RolePermissionObject = "read"
	RolePermissionObjectWrite RolePermissionObject = "write"
)

func (e RolePermissionObject) ToPointer() *RolePermissionObject {
	return &e
}

func (e *RolePermissionObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "read":
		fallthrough
	case "write":
		*e = RolePermissionObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RolePermissionObject: %v", v)
	}
}
