// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SetRequiredEngineFailedWhenInvalidEngine struct {
	// Failed to set required_engines. Required_engines must be a licensed engine
	Err *string `json:"err,omitempty"`
}
