// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SkipListAfterDeletedBlacklist struct {
}

type SkipListAfterDeletedSkip struct {
}

type SkipListAfterDeletedWhitelist struct {
}

// SkipListAfterDeleted - Object that defines the skip hashes list.
type SkipListAfterDeleted struct {
	Blacklist *SkipListAfterDeletedBlacklist `json:"blacklist,omitempty"`
	Skip      *SkipListAfterDeletedSkip      `json:"skip,omitempty"`
	Whitelist *SkipListAfterDeletedWhitelist `json:"whitelist,omitempty"`
}
