// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Blacklist struct {
}

type Skip struct {
}

type Whitelist struct {
}

// SkipList - Object that defines the skip hashes list.
type SkipList struct {
	Blacklist *Blacklist `json:"blacklist,omitempty"`
	Skip      *Skip      `json:"skip,omitempty"`
	Whitelist *Whitelist `json:"whitelist,omitempty"`
}

func (o *SkipList) GetBlacklist() *Blacklist {
	if o == nil {
		return nil
	}
	return o.Blacklist
}

func (o *SkipList) GetSkip() *Skip {
	if o == nil {
		return nil
	}
	return o.Skip
}

func (o *SkipList) GetWhitelist() *Whitelist {
	if o == nil {
		return nil
	}
	return o.Whitelist
}
