// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserRequestUISettings - Configuration of Management Console for this user.
type UserRequestUISettings struct {
}

// UserRequest - User object in MetaDefender.
type UserRequest struct {
	// Associated apikey with this user
	APIKey *string `json:"api_key,omitempty"`
	// To which User Directories belongs to (LOCAL/System/etc.)
	DirectoryID *int64 `json:"directory_id,omitempty"`
	// Which is the name showed in the Management Console
	DisplayName *string `json:"display_name,omitempty"`
	// User's email address
	Email *string `json:"email,omitempty"`
	// User's full name
	Name *string `json:"name,omitempty"`
	// The user's password
	Password *string `json:"password,omitempty"`
	// A list of roles attached to this user
	Roles []string `json:"roles,omitempty"`
	// Configuration of Management Console for this user.
	UISettings *UserRequestUISettings `json:"ui_settings,omitempty"`
}
