// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdminExportRequest struct {
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

// AdminExport500ApplicationJSON - Failed to export configuration
type AdminExport500ApplicationJSON struct {
	Err *string `json:"err,omitempty"`
}

// AdminExport405ApplicationJSON - The user has no rights for this operation.
type AdminExport405ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// AdminExport403ApplicationJSON - Invalid user information or Not Allowed
type AdminExport403ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// AdminExport400ApplicationJSON - Bad Request (e.g. invalid header, apikey is missing or invalid).
type AdminExport400ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

type AdminExportResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Request processed successfully
	AdminExport200ApplicationJSONFileString *string
	// Bad Request (e.g. invalid header, apikey is missing or invalid).
	AdminExport400ApplicationJSONObject *AdminExport400ApplicationJSON
	// Invalid user information or Not Allowed
	AdminExport403ApplicationJSONObject *AdminExport403ApplicationJSON
	// The user has no rights for this operation.
	AdminExport405ApplicationJSONObject *AdminExport405ApplicationJSON
	// Failed to export configuration
	AdminExport500ApplicationJSONObject *AdminExport500ApplicationJSON
}
