// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AnalysisRulesRequest struct {
	// The user agent string value sent in the header (specified by the client).
	//
	// Only those rules are returned, that:
	//   * Match the client's user agent sent using the user_agent header, or
	//   * Are not restricted to a specific user agent.
	//
	// For details see KB article [What are Security Policies and how do I use them?](https://onlinehelp.opswat.com/corev4/What_are_Security_Policies_and_how_do_I_use_them_.html).
	//
	UserAgent *string `header:"style=simple,explode=false,name=user_agent"`
}

func (o *AnalysisRulesRequest) GetUserAgent() *string {
	if o == nil {
		return nil
	}
	return o.UserAgent
}

// AnalysisRulesResponseBody - Unexpected event on server
type AnalysisRulesResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *AnalysisRulesResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

type ResponseBody struct {
	// The maximum allowed file size (in bytes) for this rule.
	MaxFileSize *int64 `json:"max_file_size,omitempty"`
	// A unique identifier for identify in the used rule for a scan..
	Name *string `json:"name,omitempty"`
}

func (o *ResponseBody) GetMaxFileSize() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxFileSize
}

func (o *ResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type AnalysisRulesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the list of available rules.
	Classes []ResponseBody
	// Unexpected event on server
	Object *AnalysisRulesResponseBody
}

func (o *AnalysisRulesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AnalysisRulesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AnalysisRulesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AnalysisRulesResponse) GetClasses() []ResponseBody {
	if o == nil {
		return nil
	}
	return o.Classes
}

func (o *AnalysisRulesResponse) GetObject() *AnalysisRulesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
