// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type BatchCreateRequest struct {
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey *string `header:"style=simple,explode=false,name=apikey"`
	// Select rule for the analysis, if no header given the default rule will be selected (URL encoded UTF-8 string of rule name)
	//
	Rule *string `header:"style=simple,explode=false,name=rule"`
	// Name of the batch (max 1024 bytes, URL encoded UTF-8 string).
	//
	UserData *string `header:"style=simple,explode=false,name=user-data"`
	// user_agent header used to identify (and limit) access to a particular rule. For rule selection, `rule` header should be used.
	// Since MetaDefender Core 5.6.0, when user agent is matched the predefined setting in workflow rule,  the product will return X-Core-Id containing identity of MetaDefender Core server as a header of response.
	//
	UserAgent *string `header:"style=simple,explode=false,name=user_agent"`
}

// BatchCreate500ApplicationJSON - Unexpected event on server
type BatchCreate500ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// BatchCreate403ApplicationJSON - Invalid user information or Not Allowed
type BatchCreate403ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// BatchCreate400ApplicationJSON - Bad Request (e.g. invalid header, apikey is missing or invalid).
type BatchCreate400ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

type BatchCreateResponse struct {
	// Batch created successfully.
	BatchID *shared.BatchID
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad Request (e.g. invalid header, apikey is missing or invalid).
	BatchCreate400ApplicationJSONObject *BatchCreate400ApplicationJSON
	// Invalid user information or Not Allowed
	BatchCreate403ApplicationJSONObject *BatchCreate403ApplicationJSON
	// Unexpected event on server
	BatchCreate500ApplicationJSONObject *BatchCreate500ApplicationJSON
}
