// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Metadefender/internal/sdk/pkg/models/shared"
	"bytes"
	"encoding/json"
	"errors"
	"net/http"
)

type ConfigGetSyncScanTimeoutRequest struct {
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

type ConfigGetSyncScanTimeout500ApplicationJSONType string

const (
	ConfigGetSyncScanTimeout500ApplicationJSONTypeErrorWhileRequestingConfig ConfigGetSyncScanTimeout500ApplicationJSONType = "ErrorWhileRequestingConfig"
	ConfigGetSyncScanTimeout500ApplicationJSONTypeInternalServerError        ConfigGetSyncScanTimeout500ApplicationJSONType = "InternalServerError"
)

type ConfigGetSyncScanTimeout500ApplicationJSON struct {
	ErrorWhileRequestingConfig *shared.ErrorWhileRequestingConfig
	InternalServerError        *shared.InternalServerError

	Type ConfigGetSyncScanTimeout500ApplicationJSONType
}

func CreateConfigGetSyncScanTimeout500ApplicationJSONErrorWhileRequestingConfig(errorWhileRequestingConfig shared.ErrorWhileRequestingConfig) ConfigGetSyncScanTimeout500ApplicationJSON {
	typ := ConfigGetSyncScanTimeout500ApplicationJSONTypeErrorWhileRequestingConfig

	return ConfigGetSyncScanTimeout500ApplicationJSON{
		ErrorWhileRequestingConfig: &errorWhileRequestingConfig,
		Type:                       typ,
	}
}

func CreateConfigGetSyncScanTimeout500ApplicationJSONInternalServerError(internalServerError shared.InternalServerError) ConfigGetSyncScanTimeout500ApplicationJSON {
	typ := ConfigGetSyncScanTimeout500ApplicationJSONTypeInternalServerError

	return ConfigGetSyncScanTimeout500ApplicationJSON{
		InternalServerError: &internalServerError,
		Type:                typ,
	}
}

func (u *ConfigGetSyncScanTimeout500ApplicationJSON) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	errorWhileRequestingConfig := new(shared.ErrorWhileRequestingConfig)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&errorWhileRequestingConfig); err == nil {
		u.ErrorWhileRequestingConfig = errorWhileRequestingConfig
		u.Type = ConfigGetSyncScanTimeout500ApplicationJSONTypeErrorWhileRequestingConfig
		return nil
	}

	internalServerError := new(shared.InternalServerError)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&internalServerError); err == nil {
		u.InternalServerError = internalServerError
		u.Type = ConfigGetSyncScanTimeout500ApplicationJSONTypeInternalServerError
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ConfigGetSyncScanTimeout500ApplicationJSON) MarshalJSON() ([]byte, error) {
	if u.ErrorWhileRequestingConfig != nil {
		return json.Marshal(u.ErrorWhileRequestingConfig)
	}

	if u.InternalServerError != nil {
		return json.Marshal(u.InternalServerError)
	}

	return nil, nil
}

// ConfigGetSyncScanTimeout405ApplicationJSON - The user has no rights for this operation.
type ConfigGetSyncScanTimeout405ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// ConfigGetSyncScanTimeout403ApplicationJSON - Invalid user information or Not Allowed
type ConfigGetSyncScanTimeout403ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

type ConfigGetSyncScanTimeoutResponse struct {
	// Request processed successfully.
	AdminConfigFileSync *shared.AdminConfigFileSync
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid user information or Not Allowed
	ConfigGetSyncScanTimeout403ApplicationJSONObject *ConfigGetSyncScanTimeout403ApplicationJSON
	// The user has no rights for this operation.
	ConfigGetSyncScanTimeout405ApplicationJSONObject *ConfigGetSyncScanTimeout405ApplicationJSON
	// Error while requesting configuration.
	ConfigGetSyncScanTimeout500ApplicationJSONOneOf *ConfigGetSyncScanTimeout500ApplicationJSON
}
