// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type ConfigScanHistoryRequest struct {
	AdminCleanup *shared.AdminCleanup `request:"mediaType=application/json"`
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

// ConfigScanHistory500ApplicationJSON - Unexpected event on server
type ConfigScanHistory500ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// ConfigScanHistory405ApplicationJSON - The user has no rights for this operation.
type ConfigScanHistory405ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// ConfigScanHistory403ApplicationJSON - Invalid user information or Not Allowed
type ConfigScanHistory403ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// ConfigScanHistory200ApplicationJSON - Request processed successfully
type ConfigScanHistory200ApplicationJSON struct {
	// The number of hours of data retention. Anything older than this number will be deleted.
	Cleanuprange *int64 `json:"cleanuprange,omitempty"`
}

type ConfigScanHistoryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Request processed successfully
	ConfigScanHistory200ApplicationJSONObject *ConfigScanHistory200ApplicationJSON
	// Invalid user information or Not Allowed
	ConfigScanHistory403ApplicationJSONObject *ConfigScanHistory403ApplicationJSON
	// The user has no rights for this operation.
	ConfigScanHistory405ApplicationJSONObject *ConfigScanHistory405ApplicationJSON
	// Unexpected event on server
	ConfigScanHistory500ApplicationJSONObject *ConfigScanHistory500ApplicationJSON
}
