// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type ConfigGetProxyRequest struct {
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

// ConfigGetProxy403ApplicationJSON - Invalid user information or Not Allowed
type ConfigGetProxy403ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

type ConfigGetProxyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A list of all proxy.
	ProxyList *shared.ProxyList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid user information or Not Allowed
	ConfigGetProxy403ApplicationJSONObject *ConfigGetProxy403ApplicationJSON
}
