// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type ConfigSessionRequest struct {
	AdminConfigSession *shared.AdminConfigSession `request:"mediaType=application/json"`
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

// ConfigSession500ApplicationJSON - Unexpected event on server
type ConfigSession500ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// ConfigSession405ApplicationJSON - The user has no rights for this operation.
type ConfigSession405ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// ConfigSession403ApplicationJSON - Invalid user information or Not Allowed
type ConfigSession403ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

type ConfigSessionResponse struct {
	// Request processed successfully
	AdminConfigSession *shared.AdminConfigSession
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid user information or Not Allowed
	ConfigSession403ApplicationJSONObject *ConfigSession403ApplicationJSON
	// The user has no rights for this operation.
	ConfigSession405ApplicationJSONObject *ConfigSession405ApplicationJSON
	// Unexpected event on server
	ConfigSession500ApplicationJSONObject *ConfigSession500ApplicationJSON
}
