// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type ConfigGetSkipHashRequest struct {
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

func (o *ConfigGetSkipHashRequest) GetApikey() string {
	if o == nil {
		return ""
	}
	return o.Apikey
}

// ConfigGetSkipHash500ApplicationJSON - Unexpected event on server
type ConfigGetSkipHash500ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *ConfigGetSkipHash500ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// ConfigGetSkipHash404ApplicationJSON - Requests resource was not found.
type ConfigGetSkipHash404ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *ConfigGetSkipHash404ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// ConfigGetSkipHash403ApplicationJSON - Invalid user information or Not Allowed
type ConfigGetSkipHash403ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *ConfigGetSkipHash403ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

type ConfigGetSkipHashResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A list of all skip/white/black-listed hashes.
	SkipList *shared.SkipList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid user information or Not Allowed
	ConfigGetSkipHash403ApplicationJSONObject *ConfigGetSkipHash403ApplicationJSON
	// Requests resource was not found.
	ConfigGetSkipHash404ApplicationJSONObject *ConfigGetSkipHash404ApplicationJSON
	// Unexpected event on server
	ConfigGetSkipHash500ApplicationJSONObject *ConfigGetSkipHash500ApplicationJSON
}

func (o *ConfigGetSkipHashResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ConfigGetSkipHashResponse) GetSkipList() *shared.SkipList {
	if o == nil {
		return nil
	}
	return o.SkipList
}

func (o *ConfigGetSkipHashResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ConfigGetSkipHashResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ConfigGetSkipHashResponse) GetConfigGetSkipHash403ApplicationJSONObject() *ConfigGetSkipHash403ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ConfigGetSkipHash403ApplicationJSONObject
}

func (o *ConfigGetSkipHashResponse) GetConfigGetSkipHash404ApplicationJSONObject() *ConfigGetSkipHash404ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ConfigGetSkipHash404ApplicationJSONObject
}

func (o *ConfigGetSkipHashResponse) GetConfigGetSkipHash500ApplicationJSONObject() *ConfigGetSkipHash500ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ConfigGetSkipHash500ApplicationJSONObject
}
