// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EngineConfigPutRequest struct {
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
	// The unique engine identifier
	EngineID string `pathParam:"style=simple,explode=false,name=engineId"`
}

func (o *EngineConfigPutRequest) GetApikey() string {
	if o == nil {
		return ""
	}
	return o.Apikey
}

func (o *EngineConfigPutRequest) GetEngineID() string {
	if o == nil {
		return ""
	}
	return o.EngineID
}

// EngineConfigPut500ApplicationJSON - Unexpected event on server
type EngineConfigPut500ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *EngineConfigPut500ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// EngineConfigPut405ApplicationJSON - The user has no rights for this operation.
type EngineConfigPut405ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *EngineConfigPut405ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// EngineConfigPut403ApplicationJSON - Invalid user information or Not Allowed
type EngineConfigPut403ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *EngineConfigPut403ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// EngineConfigPut400ApplicationJSON - Bad Request (e.g. invalid header, apikey is missing or invalid).
type EngineConfigPut400ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *EngineConfigPut400ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// EngineConfigPut200ApplicationJSON - Each engine has different number and types of configurations
type EngineConfigPut200ApplicationJSON struct {
}

type EngineConfigPutResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Request processed successfully
	EngineConfigPut200ApplicationJSONObject *EngineConfigPut200ApplicationJSON
	// Bad Request (e.g. invalid header, apikey is missing or invalid).
	EngineConfigPut400ApplicationJSONObject *EngineConfigPut400ApplicationJSON
	// Invalid user information or Not Allowed
	EngineConfigPut403ApplicationJSONObject *EngineConfigPut403ApplicationJSON
	// The user has no rights for this operation.
	EngineConfigPut405ApplicationJSONObject *EngineConfigPut405ApplicationJSON
	// Unexpected event on server
	EngineConfigPut500ApplicationJSONObject *EngineConfigPut500ApplicationJSON
}

func (o *EngineConfigPutResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EngineConfigPutResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EngineConfigPutResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *EngineConfigPutResponse) GetEngineConfigPut200ApplicationJSONObject() *EngineConfigPut200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.EngineConfigPut200ApplicationJSONObject
}

func (o *EngineConfigPutResponse) GetEngineConfigPut400ApplicationJSONObject() *EngineConfigPut400ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.EngineConfigPut400ApplicationJSONObject
}

func (o *EngineConfigPutResponse) GetEngineConfigPut403ApplicationJSONObject() *EngineConfigPut403ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.EngineConfigPut403ApplicationJSONObject
}

func (o *EngineConfigPutResponse) GetEngineConfigPut405ApplicationJSONObject() *EngineConfigPut405ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.EngineConfigPut405ApplicationJSONObject
}

func (o *EngineConfigPutResponse) GetEngineConfigPut500ApplicationJSONObject() *EngineConfigPut500ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.EngineConfigPut500ApplicationJSONObject
}
