// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/gerbil/terraform-provider-Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type HealthCheckRequest struct {
	// Show detailed result of health check
	Verbose *bool `queryParam:"style=form,explode=true,name=verbose"`
}

func (o *HealthCheckRequest) GetVerbose() *bool {
	if o == nil {
		return nil
	}
	return o.Verbose
}

// HealthCheckResponseBody - Unexpected event on server
type HealthCheckResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *HealthCheckResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

type HealthCheckResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unexpected event on server
	Object *HealthCheckResponseBody
	// Service is currently healthy
	Readyz *shared.Readyz
}

func (o *HealthCheckResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *HealthCheckResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *HealthCheckResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *HealthCheckResponse) GetObject() *HealthCheckResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *HealthCheckResponse) GetReadyz() *shared.Readyz {
	if o == nil {
		return nil
	}
	return o.Readyz
}
