// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type LicenseGetRequest struct {
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

func (o *LicenseGetRequest) GetApikey() string {
	if o == nil {
		return ""
	}
	return o.Apikey
}

// LicenseGetLicenseResponseBody - Unexpected event on server
type LicenseGetLicenseResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *LicenseGetLicenseResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// LicenseGetResponseBody - Invalid user information or Not Allowed
type LicenseGetResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *LicenseGetResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

type LicenseGetResponse struct {
	// Invalid user information or Not Allowed
	FourHundredAndThreeApplicationJSONObject *LicenseGetResponseBody
	// Unexpected event on server
	FiveHundredApplicationJSONObject *LicenseGetLicenseResponseBody
	// HTTP response content type for this operation
	ContentType string
	// Information about the licensed product (product type, number of activations, deploymentId, expiration date and days left)
	LicenseInformation *shared.LicenseInformation
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *LicenseGetResponse) GetFourHundredAndThreeApplicationJSONObject() *LicenseGetResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThreeApplicationJSONObject
}

func (o *LicenseGetResponse) GetFiveHundredApplicationJSONObject() *LicenseGetLicenseResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}

func (o *LicenseGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LicenseGetResponse) GetLicenseInformation() *shared.LicenseInformation {
	if o == nil {
		return nil
	}
	return o.LicenseInformation
}

func (o *LicenseGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LicenseGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
