// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ResultExportedFileRequest struct {
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
	// The data_id comes from the result of `Analyze a file`. In case of sanitizing the content of an archive, the data_id of contained file can be found in `Fetch analysis result`.
	DataID string `pathParam:"style=simple,explode=false,name=data_id"`
}

func (o *ResultExportedFileRequest) GetApikey() string {
	if o == nil {
		return ""
	}
	return o.Apikey
}

func (o *ResultExportedFileRequest) GetDataID() string {
	if o == nil {
		return ""
	}
	return o.DataID
}

// ResultExportedFile500ApplicationJSON - Unexpected event on server
type ResultExportedFile500ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *ResultExportedFile500ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// ResultExportedFile404ApplicationJSON - Requests resource was not found.
type ResultExportedFile404ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *ResultExportedFile404ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// ResultExportedFile403ApplicationJSON - Invalid user information or Not Allowed
type ResultExportedFile403ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *ResultExportedFile403ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

type ResultExportedFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the exported result PDF file
	ResultExportedFile200ApplicationPdfBinaryString []byte
	// Invalid user information or Not Allowed
	ResultExportedFile403ApplicationJSONObject *ResultExportedFile403ApplicationJSON
	// Requests resource was not found.
	ResultExportedFile404ApplicationJSONObject *ResultExportedFile404ApplicationJSON
	// Unexpected event on server
	ResultExportedFile500ApplicationJSONObject *ResultExportedFile500ApplicationJSON
}

func (o *ResultExportedFileResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ResultExportedFileResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ResultExportedFileResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ResultExportedFileResponse) GetResultExportedFile200ApplicationPdfBinaryString() []byte {
	if o == nil {
		return nil
	}
	return o.ResultExportedFile200ApplicationPdfBinaryString
}

func (o *ResultExportedFileResponse) GetResultExportedFile403ApplicationJSONObject() *ResultExportedFile403ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ResultExportedFile403ApplicationJSONObject
}

func (o *ResultExportedFileResponse) GetResultExportedFile404ApplicationJSONObject() *ResultExportedFile404ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ResultExportedFile404ApplicationJSONObject
}

func (o *ResultExportedFileResponse) GetResultExportedFile500ApplicationJSONObject() *ResultExportedFile500ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ResultExportedFile500ApplicationJSONObject
}
