// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RetrieveBlockedLeafFileRequest struct {
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey *string `header:"style=simple,explode=false,name=apikey"`
	// The data_id comes from the result of `Analyze a file`. In case of sanitizing the content of an archive, the data_id of contained file can be found in `Fetch analysis result`.
	DataID string `pathParam:"style=simple,explode=false,name=data_id"`
}

func (o *RetrieveBlockedLeafFileRequest) GetApikey() *string {
	if o == nil {
		return nil
	}
	return o.Apikey
}

func (o *RetrieveBlockedLeafFileRequest) GetDataID() string {
	if o == nil {
		return ""
	}
	return o.DataID
}

// RetrieveBlockedLeafFile500ApplicationJSON - Unexpected event on server
type RetrieveBlockedLeafFile500ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *RetrieveBlockedLeafFile500ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// RetrieveBlockedLeafFile405ApplicationJSON - The user has no rights for this operation.
type RetrieveBlockedLeafFile405ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *RetrieveBlockedLeafFile405ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// RetrieveBlockedLeafFile404ApplicationJSON - Requests resource was not found.
type RetrieveBlockedLeafFile404ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *RetrieveBlockedLeafFile404ApplicationJSON) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfoPostProcessing - Processing information
type RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfoPostProcessing struct {
	// Empty string if no action failed or list of failed actions, separated by "|".
	ActionsFailed *string
	// List of successful actions, separated by "|". Empty string if otherwise.
	ActionsRan *string
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfoPostProcessing) GetActionsFailed() *string {
	if o == nil {
		return nil
	}
	return o.ActionsFailed
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfoPostProcessing) GetActionsRan() *string {
	if o == nil {
		return nil
	}
	return o.ActionsRan
}

// RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfo - Processing information
type RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfo struct {
	// Processing information
	PostProcessing *RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfoPostProcessing
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfo) GetPostProcessing() *RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfoPostProcessing {
	if o == nil {
		return nil
	}
	return o.PostProcessing
}

type RetrieveBlockedLeafFile200ApplicationOctetStreamDetails struct {
	// Provides the reason why the file is blocked in an array (if so).
	BlockedReasons []string
	// Data identifier of this blocked leaf file.
	DataID *string
	// The name of this blocked leaf file.
	DisplayName *string
	// The filetype using mimetype.
	FileType *string
	// Data identifer of the original archive file.
	ParentID *string
	// Full path to this blocked leaf file.
	Path *string
	// Processing information
	ProcessInfo *RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfo
	// Aggregated list of potential issues of this blocked leaf file.
	Verdicts []string
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetails) GetBlockedReasons() []string {
	if o == nil {
		return nil
	}
	return o.BlockedReasons
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetails) GetDataID() *string {
	if o == nil {
		return nil
	}
	return o.DataID
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetails) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetails) GetFileType() *string {
	if o == nil {
		return nil
	}
	return o.FileType
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetails) GetParentID() *string {
	if o == nil {
		return nil
	}
	return o.ParentID
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetails) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetails) GetProcessInfo() *RetrieveBlockedLeafFile200ApplicationOctetStreamDetailsProcessInfo {
	if o == nil {
		return nil
	}
	return o.ProcessInfo
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStreamDetails) GetVerdicts() []string {
	if o == nil {
		return nil
	}
	return o.Verdicts
}

// RetrieveBlockedLeafFile200ApplicationOctetStream - Returns the list of blocked leaf files.
type RetrieveBlockedLeafFile200ApplicationOctetStream struct {
	Details []RetrieveBlockedLeafFile200ApplicationOctetStreamDetails
	// Indicates if there're indeed over 100 blocked leaf files.
	LimitReached *bool
	// Total number of files in the above array.
	Total *int64
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStream) GetDetails() []RetrieveBlockedLeafFile200ApplicationOctetStreamDetails {
	if o == nil {
		return nil
	}
	return o.Details
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStream) GetLimitReached() *bool {
	if o == nil {
		return nil
	}
	return o.LimitReached
}

func (o *RetrieveBlockedLeafFile200ApplicationOctetStream) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}

type RetrieveBlockedLeafFileResponse struct {
	Body []byte
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Requests resource was not found.
	RetrieveBlockedLeafFile404ApplicationJSONObject *RetrieveBlockedLeafFile404ApplicationJSON
	// The user has no rights for this operation.
	RetrieveBlockedLeafFile405ApplicationJSONObject *RetrieveBlockedLeafFile405ApplicationJSON
	// Unexpected event on server
	RetrieveBlockedLeafFile500ApplicationJSONObject *RetrieveBlockedLeafFile500ApplicationJSON
}

func (o *RetrieveBlockedLeafFileResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *RetrieveBlockedLeafFileResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RetrieveBlockedLeafFileResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RetrieveBlockedLeafFileResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RetrieveBlockedLeafFileResponse) GetRetrieveBlockedLeafFile404ApplicationJSONObject() *RetrieveBlockedLeafFile404ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.RetrieveBlockedLeafFile404ApplicationJSONObject
}

func (o *RetrieveBlockedLeafFileResponse) GetRetrieveBlockedLeafFile405ApplicationJSONObject() *RetrieveBlockedLeafFile405ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.RetrieveBlockedLeafFile405ApplicationJSONObject
}

func (o *RetrieveBlockedLeafFileResponse) GetRetrieveBlockedLeafFile500ApplicationJSONObject() *RetrieveBlockedLeafFile500ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.RetrieveBlockedLeafFile500ApplicationJSONObject
}
