// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type RoleCreateRequest struct {
	NewUserRoleRequest *shared.NewUserRoleRequest `request:"mediaType=application/json"`
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

func (o *RoleCreateRequest) GetNewUserRoleRequest() *shared.NewUserRoleRequest {
	if o == nil {
		return nil
	}
	return o.NewUserRoleRequest
}

func (o *RoleCreateRequest) GetApikey() string {
	if o == nil {
		return ""
	}
	return o.Apikey
}

// RoleCreateAdminResponse500ResponseBody - Unexpected event on server
type RoleCreateAdminResponse500ResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *RoleCreateAdminResponse500ResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// RoleCreateAdminResponseResponseBody - The user has no rights for this operation.
type RoleCreateAdminResponseResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *RoleCreateAdminResponseResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// RoleCreateAdminResponseBody - Invalid user information or Not Allowed
type RoleCreateAdminResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *RoleCreateAdminResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// RoleCreateResponseBody - Bad Request (e.g. invalid header, apikey is missing or invalid).
type RoleCreateResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *RoleCreateResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

type RoleCreateResponse struct {
	// Bad Request (e.g. invalid header, apikey is missing or invalid).
	FourHundredApplicationJSONObject *RoleCreateResponseBody
	// Invalid user information or Not Allowed
	FourHundredAndThreeApplicationJSONObject *RoleCreateAdminResponseBody
	// The user has no rights for this operation.
	FourHundredAndFiveApplicationJSONObject *RoleCreateAdminResponseResponseBody
	// Unexpected event on server
	FiveHundredApplicationJSONObject *RoleCreateAdminResponse500ResponseBody
	// HTTP response content type for this operation
	ContentType string
	// Request processed successfully
	NewUserRoleResponse *shared.NewUserRoleResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *RoleCreateResponse) GetFourHundredApplicationJSONObject() *RoleCreateResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredApplicationJSONObject
}

func (o *RoleCreateResponse) GetFourHundredAndThreeApplicationJSONObject() *RoleCreateAdminResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThreeApplicationJSONObject
}

func (o *RoleCreateResponse) GetFourHundredAndFiveApplicationJSONObject() *RoleCreateAdminResponseResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFiveApplicationJSONObject
}

func (o *RoleCreateResponse) GetFiveHundredApplicationJSONObject() *RoleCreateAdminResponse500ResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}

func (o *RoleCreateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RoleCreateResponse) GetNewUserRoleResponse() *shared.NewUserRoleResponse {
	if o == nil {
		return nil
	}
	return o.NewUserRoleResponse
}

func (o *RoleCreateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RoleCreateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
