// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type UserLoginRequestBody struct {
	// User's password
	Password string `json:"password"`
	// Username
	User string `json:"user"`
}

func (o *UserLoginRequestBody) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *UserLoginRequestBody) GetUser() string {
	if o == nil {
		return ""
	}
	return o.User
}

// UserLoginAuthResponseBody - Unexpected event on server
type UserLoginAuthResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *UserLoginAuthResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// UserLoginResponseBody - Invalid credentials
type UserLoginResponseBody struct {
	// <error message> will describe the incident. More details would be logged in MetaDefender Core logs
	Err *string `json:"err,omitempty"`
}

func (o *UserLoginResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

type UserLoginResponse struct {
	// Invalid credentials
	FourHundredAndThreeApplicationJSONObject *UserLoginResponseBody
	// Unexpected event on server
	FiveHundredApplicationJSONObject *UserLoginAuthResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	UserLogin *shared.UserLogin
}

func (o *UserLoginResponse) GetFourHundredAndThreeApplicationJSONObject() *UserLoginResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThreeApplicationJSONObject
}

func (o *UserLoginResponse) GetFiveHundredApplicationJSONObject() *UserLoginAuthResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}

func (o *UserLoginResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UserLoginResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UserLoginResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UserLoginResponse) GetUserLogin() *shared.UserLogin {
	if o == nil {
		return nil
	}
	return o.UserLogin
}
