// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UserChangePassRequestBody struct {
	// The new password in plain text
	NewPassword *string `json:"new_password,omitempty"`
	// The current password in plain text
	OldPassword *string `json:"old_password,omitempty"`
}

type UserChangePassRequest struct {
	RequestBody *UserChangePassRequestBody `request:"mediaType=application/json"`
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

// UserChangePass500ApplicationJSON - Unexpected event on server
type UserChangePass500ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// UserChangePass405ApplicationJSON - The user has no rights for this operation.
type UserChangePass405ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// UserChangePass400ApplicationJSON - Bad Request (e.g. invalid header, apikey is missing or invalid).
type UserChangePass400ApplicationJSON struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

// UserChangePass200ApplicationJSON - Request processed successfully
type UserChangePass200ApplicationJSON struct {
	Success *bool `json:"success,omitempty"`
}

type UserChangePassResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Request processed successfully
	UserChangePass200ApplicationJSONObject *UserChangePass200ApplicationJSON
	// Bad Request (e.g. invalid header, apikey is missing or invalid).
	UserChangePass400ApplicationJSONObject *UserChangePass400ApplicationJSON
	// The user has no rights for this operation.
	UserChangePass405ApplicationJSONObject *UserChangePass405ApplicationJSON
	// Unexpected event on server
	UserChangePass500ApplicationJSONObject *UserChangePass500ApplicationJSON
}
