// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/gerbil/terraform-provider-Metadefender/internal/sdk/pkg/models/shared"
	"net/http"
)

type YaraSourcesPutRequest struct {
	// A list of Yara Engine sources.
	YaraSourcesObject *shared.YaraSourcesObject `request:"mediaType=application/json"`
	// Generated `session_id` from [Login](/mdcore/metadefender-core/ref#userlogin) call can be used as an `apikey` for API calls that require authentication.
	//
	Apikey string `header:"style=simple,explode=false,name=apikey"`
}

func (o *YaraSourcesPutRequest) GetYaraSourcesObject() *shared.YaraSourcesObject {
	if o == nil {
		return nil
	}
	return o.YaraSourcesObject
}

func (o *YaraSourcesPutRequest) GetApikey() string {
	if o == nil {
		return ""
	}
	return o.Apikey
}

// YaraSourcesPutYaraResponseBody - Unexpected event on server
type YaraSourcesPutYaraResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *YaraSourcesPutYaraResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

// YaraSourcesPutResponseBody - Invalid user information or Not Allowed
type YaraSourcesPutResponseBody struct {
	// Error reason
	Err *string `json:"err,omitempty"`
}

func (o *YaraSourcesPutResponseBody) GetErr() *string {
	if o == nil {
		return nil
	}
	return o.Err
}

type YaraSourcesPutResponse struct {
	// Invalid user information or Not Allowed
	FourHundredAndThreeApplicationJSONObject *YaraSourcesPutResponseBody
	// Unexpected event on server
	FiveHundredApplicationJSONObject *YaraSourcesPutYaraResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A list of Yara Engine sources.
	YaraSourcesObject *shared.YaraSourcesObject
}

func (o *YaraSourcesPutResponse) GetFourHundredAndThreeApplicationJSONObject() *YaraSourcesPutResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThreeApplicationJSONObject
}

func (o *YaraSourcesPutResponse) GetFiveHundredApplicationJSONObject() *YaraSourcesPutYaraResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}

func (o *YaraSourcesPutResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *YaraSourcesPutResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *YaraSourcesPutResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *YaraSourcesPutResponse) GetYaraSourcesObject() *shared.YaraSourcesObject {
	if o == nil {
		return nil
	}
	return o.YaraSourcesObject
}
